# Generated by Django 4.1.7 on 2023-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curdapp', '0002_remove_movie_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie_images'),
        ),
    ]
